# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('fMM_rcpparma_hello_world', PACKAGE = 'fMM')
}

rcpparma_outerproduct <- function(x) {
    .Call('fMM_rcpparma_outerproduct', PACKAGE = 'fMM', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('fMM_rcpparma_innerproduct', PACKAGE = 'fMM', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('fMM_rcpparma_bothproducts', PACKAGE = 'fMM', x)
}

fM <- function(A, B) {
    .Call('fMM_fM', PACKAGE = 'fMM', A, B)
}

